// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1EwVadFO3wsvHTA5Hoil3BR5kAnIhURw',
    appId: '1:893369469150:web:2043ea445c983033a3da4f',
    messagingSenderId: '893369469150',
    projectId: 'profinixtechnologies-pr75',
    authDomain: 'profinixtechnologies-pr75.firebaseapp.com',
    databaseURL: 'https://profinixtechnologies-pr75-default-rtdb.firebaseio.com',
    storageBucket: 'profinixtechnologies-pr75.appspot.com',
    measurementId: 'G-0P9NT3031G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAemHdMhstxoJk5r1q7zC_wqzOG52vwSm0',
    appId: '1:893369469150:android:84e030c2a04ad11fa3da4f',
    messagingSenderId: '893369469150',
    projectId: 'profinixtechnologies-pr75',
    databaseURL: 'https://profinixtechnologies-pr75-default-rtdb.firebaseio.com',
    storageBucket: 'profinixtechnologies-pr75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWuq-H-0RU0BKE0-a622tKlc29RQIGmBA',
    appId: '1:893369469150:ios:224b65c6e8541b44a3da4f',
    messagingSenderId: '893369469150',
    projectId: 'profinixtechnologies-pr75',
    databaseURL: 'https://profinixtechnologies-pr75-default-rtdb.firebaseio.com',
    storageBucket: 'profinixtechnologies-pr75.appspot.com',
    androidClientId: '893369469150-8du3f840hbrrj4vn91fa7v44vrmeild8.apps.googleusercontent.com',
    iosClientId: '893369469150-3euf5s5kgthjcjnnif7144um1oci96ku.apps.googleusercontent.com',
    iosBundleId: 'com.agentiqminds.app',
  );
}
