const Map<String, Map<String, String>> speechLocalesMap = {
  "American": {"English (United States)": "en-US"},
  "Indian": {
    "Hindi (India)": "hi-IN",
    "Tamil (India)": "ta-IN",
    "Telugu (India)": "te-IN",
    "Gujarati (India)": "gu-IN",
    "Marathi (India)": "mr-IN",
    "Kannada (India)": "kn-IN",
    "Malayalam (India)": "ml-IN",
    "Punjabi (India)": "pa-IN",
    "Bengali (India)": "bn-IN",
    "Urdu (India)": "ur-IN",
    "English (India)": "en-IN",
  },
  "Arabic": {
    "Arabic (UAE)": "ar-AE",
    "Arabic (Saudi Arabia)": "ar-SA",
    "Arabic (Egypt)": "ar-EG",
    "Arabic (Iraq)": "ar-IQ",
    "Arabic (Jordan)": "ar-JO",
    "Arabic (Kuwait)": "ar-KW",
    "Arabic (Lebanon)": "ar-LB",
    "Arabic (Morocco)": "ar-MA",
    "Arabic (Qatar)": "ar-QA",
    "Arabic (Syria)": "ar-SY",
    "Arabic (Tunisia)": "ar-TN",
    "Arabic (Oman)": "ar-OM",
  },
  "Spanish": {
    "Spanish (Spain)": "es-ES",
    "Spanish (Mexico)": "es-MX",
    "Spanish (Argentina)": "es-AR",
    "Spanish (Colombia)": "es-CO",
    "Spanish (Chile)": "es-CL",
    "Spanish (Peru)": "es-PE",
    "Spanish (United States)": "es-US",
  },
  "French": {
    "French (France)": "fr-FR",
    "French (Canada)": "fr-CA",
    "French (Switzerland)": "fr-CH",
    "French (Belgium)": "fr-BE",
  },
  "German": {
    "German (Germany)": "de-DE",
    "German (Austria)": "de-AT",
    "German (Switzerland)": "de-CH",
  },
  "Italian": {"Italian (Italy)": "it-IT", "Italian (Switzerland)": "it-CH"},
  "Portuguese": {
    "Portuguese (Portugal)": "pt-PT",
    "Portuguese (Brazil)": "pt-BR",
  },
  "Russian": {"Russian (Russia)": "ru-RU"},
  "Japanese": {"Japanese (Japan)": "ja-JP"},
  "Korean": {"Korean (South Korea)": "ko-KR"},
  "Chinese": {
    "Chinese (Mandarin, Simplified)": "zh-CN",
    "Chinese (Cantonese, Traditional)": "zh-HK",
    "Chinese (Mandarin, Traditional)": "zh-TW",
  },
  "Turkish": {"Turkish (Turkey)": "tr-TR"},
  "Thai": {"Thai (Thailand)": "th-TH"},
  "Polish": {"Polish (Poland)": "pl-PL"},
  "Dutch": {"Dutch (Netherlands)": "nl-NL", "Dutch (Belgium)": "nl-BE"},
  "Scandinavian": {
    "Swedish (Sweden)": "sv-SE",
    "Norwegian (Norway)": "nb-NO",
    "Finnish (Finland)": "fi-FI",
    "Danish (Denmark)": "da-DK",
  },
  "Central & Eastern European": {
    "Czech (Czech Republic)": "cs-CZ",
    "Hungarian (Hungary)": "hu-HU",
    "Greek (Greece)": "el-GR",
  },
  "Southeast Asian": {
    "Indonesian (Indonesia)": "id-ID",
    "Malay (Malaysia)": "ms-MY",
    "Vietnamese (Vietnam)": "vi-VN",
  },
};
